### ISSUE TITLE
Consider whether we should require (or even allow) a password for private keys

### ISSUE THREAD

**Issue by samgomena** [securemailbox/cli#18]
When creating a private key, the CLI prompts the user to give a password for their key. Using a password isn't required by our requirements and possibly goes against them. It also doesn't appear to be required:
```python
import gnupg
gpg_input = gpg.gen_key_input(key_type="RSA", key_length=4096, passphrase=None)

# Works
gpg.gen_key(gpg_input)
```

**Comment by xingchengyusi** [comment]
Thank you, Sam. That is an excellent way to avoid prompt password every time.

**Comment by xingchengyusi** [comment]
There is bad news that is this way partly work. When I try some like:
```
password = None
key = ctx.parent.gpg.create(password=password, name=name, email=email,
                            key_type=key_type, key_length=key_length,
                            expire_date=expire_date)
```
No error returned, look like it creates a "no password" key successful. And then, follow the code used to decrypt the message.
```
msg = self.gpg.decrypt(message=message)
# or
msg = self.gpg.decrypt(message=message, passphrase=None)
```
The enter password prompt also pops. I try several times and find what `python-gnupg` do from source code that is set `None` string as the password. That means below one work:
```
msg = self.gpg.decrypt(message=message, passphrase='None')
```
In this case, if the password is not required or possibly be against, the default password should be set. Overall, that looks good to me.

**Comment by xingchengyusi** [comment]
During creating the key, the client does not allow the user to enter their own password and set default password as `None`.
During encrypting, the client asks the user whether they want to use their own passphrase. If they not, the password should be `None`.
