### ISSUE TITLE
Private key password prompt not continuing in create-key

### ISSUE THREAD

**Issue by andrewbespaly** [securemailbox/cli#19]
When creating a key through the prompts, after entering the "Enter private key password" prompt, nothing happens and I'm stuck in the console not able to exit.
For it to work I have to run:
"pipenv run python scmail.py create-key -n [name] -e [email] -t RSA -l 1024 -d 2y -p [password]" instead of "pipenv run python scmail.py create-key"

I'm running on Windows 10 64 bit. 
To reproduce:
with the CLI directory open, open Git Bash and write: pipenv run python scmail.py create-key, and follow the prompts

**Comment by xingchengyusi** [comment]
Thanks, Andrew. I know it.

**Comment by xingchengyusi** [comment]
This happened when a prompt try to hide the input out of the `pipenv shell`. Sorry about I cannot fix it by this way since the password input should be hide regularly. I will continue works on this problem to see if there are other methods to fix.
Did you want to try the following command, that works for me in Git Bash?

```bash
py -m pipenv shell
python scmail.py create-key
```

**Comment by xingchengyusi** [comment]
This seems a known issue with Git Bash.
See https://github.com/SBoudrias/Inquirer.js/issues/421
Several methods could try to avoid it.
First is run:
```
winpty py -m pipenv run python scmail.py create-key
```
Second is running the `Git/bin/bash.exe`, not the `Git/git-bash.exe`.
Those three (add run `pipenv shell`) all work for me.

Cause my environment setting problem, I use `py -m pipenv` instead directly run `pipenv`(and the same issue reproduce.

**Comment by andrewbespaly** [comment]
`py -m pipenv shell`
`python scmail.py create-key`

didn't work for me, but 

`winpty py -m pipenv run python scmail.py create-key`
did

I guess we could just add something in the readme that says to use that instead.
Does this happen because I'm on windows, or for some other reason?

**Comment by xingchengyusi** [comment]
@andrewbespaly I not really sure since my poor windows experience.
I google and find that this is a git bash issue cause it is not a tty terminal. The `winpty` provide a new, hidden console can solve this problem. In this case, the passphrase is properly hidden on `PowerShell` or `cmd`.
